export default [
        {
            year: `2019`,
            stages: ['main', 'forte'],
            days: ['16/08', '17/08'],
            urlGallery: ``,
            desc: ``,
            lineup: [
                {
                    name: `Fuoriology`,
                    youtubeKey: `gJjew3vnZ6k`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `Earth Beat Movement`,
                    youtubeKey: `IaqKXbKAOeU`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `Mole Moonwalktet`,
                    youtubeKey: `JzCIUPWVTEI`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `Gold Miners NightClub`,
                    youtubeKey: `V15vRciah-s`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `Dolomhate`,
                    youtubeKey: `sw9OatbbsIU`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `Elena Mazzon`,
                    youtubeKey: `CmqaF7_X_P4`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 2,
                    day: 1,
                },
                {
                    name: `Da Quagga`,
                    youtubeKey: `Pi7kWRtcTCQ`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 2,
                    day: 1,
                },
                {
                    name: `Untamed Sound System`,
                    youtubeKey: `n0FGhAP_mCw`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 2,
                    day: 1,
                },
            ],
        },
        {
            year: `2018`,
            stages: ['main'],
            days: ['17/08', '18/08'],
            urlGallery: ``,
            desc: ``,
            lineup: [
                {
                    name: `Drowning Thy Issues`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Maddox`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Maim`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Overunit Machine`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `East Sunset`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `Bobo Children`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `O'Ciucciariello`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
                {
                    name: `Maci's Mobile`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 2,
                },
            ],
        },
        {
            year: `2017`,
            stages: ['main'],
            days: ['26/08'],
            urlGallery: ``,
            desc: ``,
            lineup: [
                {
                    name: `Riah`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Kanseil`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `The Grinders`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Full Leather Jackets`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Anterra`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `The Young Tree`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
            ],
        },
        {
            year: `2015`,
            stages: ['main'],
            days: ['29/08'],
            urlGallery: ``,
            desc: ``,
            lineup: [
                {
                    name: `Dirty Speed`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Never Night`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `High Voltage`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Full Leather Jackets`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Modalitá Litfiba`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Wild Roses`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
            ],
        },
        {
            year: `2014`,
            stages: ['main'],
            days: ['30/08'],
            urlGallery: ``,
            desc: ``,
            lineup: [
                {
                    name: `Octadrum`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Overload`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: ``,
                    youtubeKey: `High Voltage`,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Full Leather Jackets`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Wild Roses`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Sonicroom`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
                {
                    name: `Senza Filtro`,
                    youtubeKey: ``,
                    urlSocial1: ``,
                    urlSocial2: ``,
                    stage: 1,
                    day: 1,
                },
            ],
        }
    ];